export const CART_ACTION_TYPES = {
	SET_IS_CART_OPEN: 'cart/SET_IS_CART_OPEN',
	SET_CART_ITEMS: 'cart/SET_CART_ITEMS',
	ADD_CART_ITEM: 'cart/ADD_CART_ITEM',
	REMOVE_CART_ITEM: 'cart/REMOVE_CART_ITEM',
	CLEAR_CART_ITEMS: 'cart/CLEAR_CART_ITEMS',
};
